version: "3.2"
services:
  mysql57:
    container_name: conf<project.name>_mysql57
    restart: unless-stopped
    build: './containers/mysql/'
    volumes:
      - conf<project.name>_mysql57:/var/lib/mysql:delegated
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  mysql57:

networks:
  default:
    external:
      name: deckle