version: "3.2"
services:
  apache:
    container_name: conf<project.name>
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=web,websecure"
      - "traefik.http.routers.apache-conf<project.name>.rule=Host(`conf<project.name>.docker.local`)"
    build: './containers/apache/'
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ~/.composer:/root/.composer
    environment:
      PHP_IDE_CONFIG: serverName=${COMPOSE_PROJECT_NAME}

networks:
  default:
    external:
      name: common
